# Generated by Django 5.2.5 on 2025-08-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddJuries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='user_Image')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Father Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('work_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Work place')),
                ('academic_degree', models.CharField(blank=True, max_length=255, null=True, verbose_name='Academic Degree')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession')),
                ('login', models.CharField(blank=True, max_length=255, null=True, verbose_name='Login')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'Jury',
                'verbose_name_plural': 'Juries',
            },
        ),
    ]
