# Generated by Django 5.2.5 on 2025-08-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddJuries',
            new_name='AddJury',
        ),
    ]
