# Generated by Django 5.2.5 on 2025-08-27 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_children_image'),
        ('competition', '0008_delete_competitionpayment'),
        ('juries', '0002_rename_addjuries_addjury'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Score')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_grades', to='children.children', verbose_name='Child')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_grades', to='competition.competition', verbose_name='Competition')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='juries.addjury', verbose_name='Jury')),
            ],
            options={
                'verbose_name': 'jury grade',
                'verbose_name_plural': 'jury grades',
                'unique_together': {('competition', 'child', 'jury')},
            },
        ),
    ]
