# Generated by Django 5.2.5 on 2025-08-20 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_alter_header_options_alter_title_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(upload_to='galleries', verbose_name='Gallery Image')),
                ('description', models.TextField(verbose_name='Gallery Description')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='home.title', verbose_name='Gallery Title')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
