# Generated by Django 5.2.5 on 2025-08-19 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('father_name', models.CharField(max_length=255, verbose_name='Father Name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('study_place', models.CharField(max_length=255, verbose_name='Study Place')),
                ('type_of_kind', models.CharField(choices=[('son', 'Son'), ('daughter', 'Daughter')], max_length=10, verbose_name='Type of Kind')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Parent')),
            ],
        ),
    ]
