# Generated by Django 5.2.5 on 2025-08-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Child Image'),
        ),
    ]
