# Generated by Django 5.2.5 on 2025-08-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_addjuries_remove_user_academic_degree_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addjuries',
            options={'verbose_name': 'Jury', 'verbose_name_plural': 'Juries'},
        ),
    ]
