# Generated by Django 5.2.5 on 2025-08-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_addjuries_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddJuries',
        ),
    ]
