# Generated by Django 5.2.5 on 2025-08-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contactus_options_alter_subscribe_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='contactus',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.title', verbose_name='contact info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='contact', verbose_name='contact info image'),
        ),
    ]
