# Generated by Django 5.2.5 on 2025-08-20 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_contactinfo_contactus_contactinfo_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('number', models.CharField(blank=True, max_length=250, null=True, verbose_name='number')),
                ('image', models.ImageField(blank=True, upload_to='number', verbose_name='image')),
                ('contact_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contactus', verbose_name='numbers')),
            ],
            options={
                'verbose_name': 'Contact number',
                'verbose_name_plural': 'Contact numbers',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(blank=True, upload_to='location', verbose_name='image')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contactus', verbose_name='location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
