# Generated by Django 5.2.5 on 2025-08-21 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactnumber_location_delete_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(blank=True, upload_to='social-media', verbose_name='image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.title', verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
