# Generated by Django 5.2.5 on 2025-08-19 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_alter_header_options_alter_title_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='competition_images/', verbose_name='Images')),
                ('description', models.TextField(verbose_name='description')),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='home.title', verbose_name='title')),
            ],
            options={
                'verbose_name': 'competition',
                'verbose_name_plural': 'competitions',
                'ordering': ['-deadline'],
            },
        ),
    ]
