# Generated by Django 5.2.5 on 2025-08-19 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('home', '0002_alter_header_options_alter_title_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='competition_images/', verbose_name='Images')),
                ('description', models.TextField(verbose_name='description')),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='home.title', verbose_name='title')),
            ],
            options={
                'verbose_name': 'competition',
                'verbose_name_plural': 'competitions',
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('physical_certificate', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('payme', 'Payme'), ('click', 'Click')], max_length=20, null=True)),
                ('children', models.ManyToManyField(related_name='applications', to='children.children')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='competition.competition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
