# Generated by Django 5.2.5 on 2025-08-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name='age'),
            preserve_default=False,
        ),
    ]
