# Generated by Django 5.2.5 on 2025-08-21 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competition_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-end_date'], 'verbose_name': 'competition', 'verbose_name_plural': 'competitions'},
        ),
        migrations.RemoveField(
            model_name='competition',
            name='deadline',
        ),
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='age',
            field=models.CharField(max_length=20, verbose_name='age'),
        ),
    ]
