# Generated by Django 5.2.5 on 2025-08-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_competitionsubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionsubscriber',
            options={'verbose_name': 'Competition Subscriber', 'verbose_name_plural': 'Competition Subscribers'},
        ),
        migrations.AddField(
            model_name='competition',
            name='about_competition',
            field=models.TextField(default=1, verbose_name='about competition'),
            preserve_default=False,
        ),
    ]
