# Generated by Django 5.2.5 on 2025-08-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_alter_competitionsubscriber_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.PositiveIntegerField(default=0, verbose_name='participants'),
        ),
    ]
