# Generated by Django 5.2.5 on 2025-08-25 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_competition_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='payment ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date time')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
